[snowflake]
username = "NAMANUPADHYE3000"
password = "Naman@40115570"
account = "izmzdbz-llb46798"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "MAIN_RAG_DB"
schema = "MAIN_RAG_SCHEMA"

[newsapi]
apikey = "5eb7fffe17364f9bbce3e17dbeddd867"

[difbot]
apikey = "3130e6ff0e12e6877f3b7739d440d539"